Update build-push.yml

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -3,8 +3,6 @@ name: Build and Publish Docker image
 on:
   push:
     branches: [ "master" ]
-  pull_request:
-    branches: [ "master" ]
 
 env:
   REGISTRY: docker.io
@@ -30,6 +28,14 @@ jobs:
       - name: Build with Maven
         run: mvn clean package
 
+      - name: Verify JAR exists
+        run: |
+          if [ ! -f "target/"*.jar ]; then
+            echo "Error: No JAR file found in target directory!"
+            ls -la target/
+            exit 1
+          fi
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -42,3 +48,4 @@ jobs:
           context: .
           push: true
           tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
+          file: ./Dockerfile
